<div class="row">
	<div class="span6 offset3"> <!-- LADO ESQUERDO -->

		<div class="widget widget-table action-table">
			<div class="widget-header">
				<i class="icon-picture"></i>
				<h3>imagens</h3>
			</div> <!-- /widget-header -->



			<div class="widget-content">
				<table class="table table-striped table-bordered">
					<thead>
						<tr>
							<th>Id</th>
							<th>Data</th>
							<th>Imagem</th>
							<th class="td-actions">Ações</th>
						</tr>
					</thead>
					<tbody>

					<? foreach ( $info as $i): 
							extract($i) ?>
												
						<tr> 
							<td><?= $id_imagens ?></td>
							<td><?= date("d/m/Y - H:m:s", strtotime($created)) ?></td>
							<td><img src="<?= URL ?>files/<?= $imagem ?>" width="200"></td>
							
							<td class='td-actions'>

								<!-- EDITAR -->
								<a title='editar' href='<?= URL ?>admin/edit/imagens/<?= $id_imagens ?>' class='btn btn-small btn-success'>
									<i class='btn-icon-only icon-pencil'></i>
								</a>
								
								<!-- EXCLUIR -->
								<a id="delete<?= $id_imagens ?>" title='excluir' data='<?= URL ?>admin/del/imagens/<?= $id_imagens ?>' onclick="del(this.id)" class='btn btn-small btn-danger'>
									<i class='btn-icon-only icon-remove'></i>
								</a>
							</td>
						</tr>

					<? endforeach; ?>									

					</tbody>
				</table>
			</div> <!-- /widget-content -->						
		</div> <!-- /widget -->	

		<!-- PAGINAÇÃO -->

		<?= $this -> pagination -> view(); ?>

		<!-- FIM PAGINAÇÃO -->

</div> <!-- row -->



<script type="text/javascript">

	$('input[name="destaque"]').change(function() {
		this.form.submit(function(e){
			e.preventDefault();
		});
	});

</script>
